# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    encoders:
        Ynlo\GraphQLBundle\Demo\ApiDemoBundle\Entity\User:
            algorithm: md5
            encode_as_base64: false
            iterations: 1

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        in_memory:
            memory: ~

    firewalls:
       public:
              methods: [HEAD]
              pattern: ^/v\d+
              security: false